[package]
name = "api"
version = "0.1.0"
authors = ["CyanFroste <cyan14froste@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "api"
path = "lib.rs"

[dependencies]
rand = "0.7.3"